// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yeyhgvpnhhqrkolypxdw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlleWhndnBuaGhxcmtvbHlweGR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1MTM2NDksImV4cCI6MjA2MzA4OTY0OX0.ml79msUg9jF20OpiQcWX9u_5o4cJ6TEIZay3_rGWT2g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

export const SUPABASE_ANON_KEY = SUPABASE_PUBLISHABLE_KEY;
